name: Minify CSS on Merge to Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  minify-css:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install CSS minifier
      run: npm install -g csso-cli

    - name: Minify CSS file
      run: csso dist/style.css --output dist/style.min.css

    - name: Commit and push minified CSS
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dist/style.min.css
        git commit -m "Add minified CSS file"
        git push
